apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-pvc
spec:
  accessModes:
   - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      name: prometheus